### ISSUE TITLE
The Bert model

### ISSUE THREAD

**Issue by wangleishan** [yangyn533/HCRNet#2]
May I ask if you used the training model of 'DNABert' directly or fine-tuned it? 
I see  that you are using the model directly in the code, but in the article you say fine-tuning it.

**Comment by yangyn533** [comment]
We open source the fine-tuned bert model, since it is fine-tuned based on the DNABERT model, so the number of parameters is consistent.

**Comment by wangleishan** [comment]
OK，thank you for your reply！
